export type SpectrumColor =
  | "red"
  | "orange"
  | "amber"
  | "lime"
  | "green"
  | "teal"
  | "cyan"
  | "blue"
  | "indigo"
  | "violet"
  | "magenta"
  | "pink"
  | "chalk"
  | "onyx"
  | "sand";

export const swatchClass: Record<SpectrumColor, string> = {
  red: "bg-spectrum-red",
  orange: "bg-spectrum-orange",
  amber: "bg-spectrum-amber",
  lime: "bg-spectrum-lime",
  green: "bg-spectrum-green",
  teal: "bg-spectrum-teal",
  cyan: "bg-spectrum-cyan",
  blue: "bg-spectrum-blue",
  indigo: "bg-spectrum-indigo",
  violet: "bg-spectrum-violet",
  magenta: "bg-spectrum-magenta",
  pink: "bg-spectrum-pink",
  chalk: "bg-spectrum-chalk",
  onyx: "bg-spectrum-onyx",
  sand: "bg-spectrum-sand",
};

export const textClass: Record<SpectrumColor, string> = {
  red: "text-spectrum-red",
  orange: "text-spectrum-orange",
  amber: "text-spectrum-amber",
  lime: "text-spectrum-lime",
  green: "text-spectrum-green",
  teal: "text-spectrum-teal",
  cyan: "text-spectrum-cyan",
  blue: "text-spectrum-blue",
  indigo: "text-spectrum-indigo",
  violet: "text-spectrum-violet",
  magenta: "text-spectrum-magenta",
  pink: "text-spectrum-pink",
  chalk: "text-ink",
  onyx: "text-spectrum-onyx",
  sand: "text-spectrum-sand",
};

export const softBgClass: Record<SpectrumColor, string> = {
  red: "bg-spectrum-red-soft",
  orange: "bg-spectrum-orange-soft",
  amber: "bg-spectrum-amber-soft",
  lime: "bg-spectrum-lime-soft",
  green: "bg-spectrum-green-soft",
  teal: "bg-spectrum-teal-soft",
  cyan: "bg-spectrum-cyan-soft",
  blue: "bg-spectrum-blue-soft",
  indigo: "bg-spectrum-indigo-soft",
  violet: "bg-spectrum-violet-soft",
  magenta: "bg-spectrum-magenta-soft",
  pink: "bg-spectrum-pink-soft",
  chalk: "bg-spectrum-chalk-soft",
  onyx: "bg-spectrum-onyx-soft",
  sand: "bg-spectrum-sand-soft",
};

export const borderAccentClass: Record<SpectrumColor, string> = {
  red: "border-spectrum-red",
  orange: "border-spectrum-orange",
  amber: "border-spectrum-amber",
  lime: "border-spectrum-lime",
  green: "border-spectrum-green",
  teal: "border-spectrum-teal",
  cyan: "border-spectrum-cyan",
  blue: "border-spectrum-blue",
  indigo: "border-spectrum-indigo",
  violet: "border-spectrum-violet",
  magenta: "border-spectrum-magenta",
  pink: "border-spectrum-pink",
  chalk: "border-spectrum-chalk",
  onyx: "border-spectrum-onyx",
  sand: "border-spectrum-sand",
};

export const onAccentTextClass: Record<SpectrumColor, string> = {
  red: "text-spectrum-red",
  orange: "text-spectrum-orange",
  amber: "text-spectrum-amber",
  lime: "text-spectrum-lime",
  green: "text-spectrum-green",
  teal: "text-spectrum-teal",
  cyan: "text-spectrum-cyan",
  blue: "text-spectrum-blue",
  indigo: "text-spectrum-indigo",
  violet: "text-spectrum-violet",
  magenta: "text-spectrum-magenta",
  pink: "text-spectrum-pink",
  chalk: "text-ink",
  onyx: "text-spectrum-onyx",
  sand: "text-spectrum-sand",
};

export function spectrum(colour: string): SpectrumColor {
  return colour in swatchClass ? (colour as SpectrumColor) : "red";
}

export type Decoration = {
  slug: string;
  name: string;
  colour: SpectrumColor;
  what: string;
  bestFor: string;
  colourLimit: string;
  leadTime: string;
  artwork: string;
  advantages?: string[];
  limitations?: string[];
};

export const decorations: Decoration[] = [
  {
    slug: "screen-print",
    name: "Screen Print",
    colour: "red",
    what: "Screen Printing is achieved by forcing ink through a fine mesh screen with a squeegee onto the product and is ideal for branding flat objects.",
    bestFor: "Flat products, large print areas, white or light-coloured products, select textile products",
    colourLimit: "Up to five colours with tight multi-colour registration; fluorescent, metallic gold and silver inks available on select textile products",
    leadTime: "Most screen print inks dry quickly and can be shipped immediately after printing",
    artwork: "Editable vector artwork required. Fonts should be converted to outlines/objects to avoid font conflicts.",
    advantages: [
      "Large print areas are possible on flat products",
      "Close PMS matches are possible on white or light-coloured products",
      "Most screen print inks dry quickly and can be shipped immediately after printing",
      "Fluorescent, metallic gold and silver inks are available on select textile products",
      "Many products can print with tight multi-colour registration, with some products able to be printed using up to five colours",
    ],
    limitations: [
      "Close PMS matches are more difficult on darker products and will only be approximate. In some instances, a white base will create a better print",
      "Unable to print variable data",
      "Each colour requires its own setup charge",
    ],
  },
  {
    slug: "embroidery",
    name: "Embroidery",
    colour: "orange",
    what: "An excellent way of branding bags, apparel, and other textile products. It offers higher perceived value and a depth of branding quality which other processes cannot match. Embroidery uses rayon thread which is stitched into the product and has a slightly raised effect.",
    bestFor: "Caps, beanies, polos, jackets, backpacks, bags and other textile products",
    colourLimit: "Up to 12 thread colours with approximate PMS matching. Metallic embroidery colours have special pricing.",
    leadTime: "10–12 working days (plus one-off digitising)",
    artwork: "Editable vector artwork required. Fonts should be converted to outlines/objects. Avoid fine detail — minimum text heights are 4.5mm for Sans Serif fonts and 5.5mm for Serif fonts.",
    advantages: [
      "Higher perceived value and depth of branding quality",
      "Only one setup charge applies per position for up to 12 thread colours",
    ],
    limitations: [
      "Only approximate PMS colour matches are possible - threads are chosen from available colours to give the closest possible match",
      "Unable to print variable data such as individual naming",
      "Metallic embroidery colours have special pricing",
    ],
  },
  {
    slug: "pad-print",
    name: "Pad Print",
    colour: "amber",
    what: "Pad printing uses a silicone pad to transfer an image to a product from a laser etched printing plate. It is one of the most popular and affordable ways of branding promotional products due to its ability to reproduce images on uneven or curved products and print multiple colours in a single pass.",
    bestFor: "Pens, drinkware, USB drives, small tech and uneven or curved promotional products",
    colourLimit: "Up to 6 spot colours with tight multi-colour registration. Metallic gold and silver ink available. White under base available for darker products.",
    leadTime: "7–9 working days; some inks require a curing period before shipping",
    artwork: "Vector editable artwork required. Fonts should be converted to outlines/objects. Minimum detail 0.4mm, minimum text size 5pt.",
    advantages: [
      "Ideal for printing on curved or uneven products",
      "Prints sharp, clean images with detail as fine as 0.4mm; minimum text size is 5pt",
      "Close PMS matches are possible on white or light-coloured products",
      "Metallic gold and silver ink are available",
      "Can offer a white under base for darker products that require it",
      "Many products can print up to 6 colours with tight multi-colour registration",
    ],
    limitations: [
      "Halftones cannot be consistently reproduced",
      "Unable to print variable data such as individual naming",
      "Close PMS matches are more difficult on darker products and will only be approximate; a white base creates a better print",
      "Some pad print inks require a curing period before the product can be shipped",
      "Each colour requires its own setup charge",
      "Neon/fluorescent colours are not available",
    ],
  },
  {
    slug: "laser-engraving",
    name: "Laser Engraving",
    colour: "green",
    what: "Laser engraving is a permanent branding process that engraves artwork into the surface of the product using a laser. Different materials produce different engraving finishes, so pre-production samples are recommended to avoid uncertainty.",
    bestFor: "Metal pens, stainless drinkware, bamboo, cork, leather and products needing a permanent engraved finish",
    colourLimit: "Single tone — the natural colour of the exposed substrate",
    leadTime: "7–9 working days; product can be shipped straight away after engraving",
    artwork: "Editable vector artwork required. Fonts should be converted to outlines/objects. Gradients cannot be reproduced.",
    advantages: [
      "Higher perceived value than other forms of branding",
      "The branding becomes part of the surface and is permanent",
      "Large branding areas available on curved products",
      "Variable data including individual names is available on select products",
      "The product can be shipped straight away after being engraved",
    ],
    limitations: [
      "Fine detail can be lost on smaller products like pens",
    ],
  },
  {
    slug: "digital-uv-print",
    name: "Digital UV Print",
    colour: "cyan",
    what: "Full-colour inkjet cured instantly with UV light, printed straight onto the product.",
    bestFor: "Notebooks, drinkware, chargers, boxes, photographic artwork",
    colourLimit: "Unlimited CMYK, plus white underbase on dark products",
    leadTime: "6–8 working days",
    artwork: "300dpi raster (PNG, TIFF, PDF) or vector, in CMYK.",
  },
  {
    slug: "debossing",
    name: "Debossing",
    colour: "indigo",
    what: "Commonly referred to as ‘Blind’ debossing, a heated custom metal plate is pressed firmly onto the product leaving an impression of the artwork.",
    bestFor: "PU and leather notebooks, cases, tags, journals",
    colourLimit: "Blind (no colour) or a two-tone finish on certain products",
    leadTime: "Can be shipped straight after heat pressing is finished",
    artwork: "Vector artwork with a minimum line thickness of 0.4mm. Fine detail may fill in under pressure.",
    advantages: [
      "Higher perceived value than other forms of branding",
      "The branding becomes part of the product and is permanent",
      "The product can be shipped as soon as heat pressing is finished",
      "Certain products can produce a two-tone finish",
    ],
    limitations: [
      "Can be very subtle and harder to see, especially on textured materials",
      "Unable to print variable data such as individual naming",
      "Minimum line thickness: 0.4mm",
    ],
  },
  {
    slug: "full-colour-wrap",
    name: "Full-Colour Wrap",
    colour: "violet",
    what: "A printed film wrapped around the whole product for edge-to-edge, seam-free coverage.",
    bestFor: "Bottles, tumblers, can coolers, desk mats, all-over artwork",
    colourLimit: "Unlimited CMYK with photographic detail",
    leadTime: "9–11 working days",
    artwork: "Supplied to our wrap template at 300dpi with 3mm bleed.",
  },
  {
    slug: "doming",
    name: "Doming",
    colour: "magenta",
    what: "A printed label finished with a clear polyurethane dome that magnifies the artwork and shrugs off scratches.",
    bestFor: "Cables, keyrings, trucker caps, chargers, badges",
    colourLimit: "Unlimited CMYK plus metallic bases",
    leadTime: "9–11 working days",
    artwork: "Vector or 300dpi raster with a defined outer cut shape.",
  },
  {
    slug: "colourflex-transfer",
    name: "Colourflex Transfer",
    colour: "pink",
    what: "A CMYK+W digital print process for apparel and fabrics. It produces high-definition, vibrant artwork with a soft-touch matt finish and efficient self-weeding technology.",
    bestFor: "Tees, hoodies, apparel, bags and fabric items needing full-colour or photographic artwork",
    colourLimit: "Full CMYK + white underbase; approximate spot colours. Metallic and neon/fluorescent colours cannot be reproduced.",
    leadTime: "6–8 working days; can be shipped straight after printing",
    artwork: "Vector or bitmap at 300DPI at actual print size. Fonts should be converted to outlines/objects. Minimum detail 1mm.",
  },
  {
    slug: "digiflex-transfer",
    name: "DigiFlex Transfer",
    colour: "amber",
    what: "DigiFlex Transfer is a DTF or Direct to Film digital transfer process, used for branding apparel and fabrics.",
    bestFor: "Tees, hoodies, apparel, bags and fabric items needing full-colour, personalised or variable-data artwork",
    colourLimit: "Full colour digital transfer. Metallic and neon/fluorescent colours cannot be reproduced.",
    leadTime: "Can be shipped straight after being printed",
    artwork: "Vector or bitmap at 300DPI at actual print size. Fonts should be converted to outlines/objects. Minimum detail 1mm.",
    advantages: [
      "More economical for short runs",
      "Ideal for personalisation and variable data, including names and numbering",
      "Eco-friendly water-based inks",
      "Durable, flexible branding for apparel that is machine washable",
      "Efficient self-weeding technology",
      "Only one set up charge is required regardless of the number of print colours",
      "Can be shipped straight after being printed",
    ],
    limitations: [
      "Some colours cannot be reproduced including metallic and neon/fluorescent colours",
      "Minimum detail advised at 1mm",
    ],
  },
  {
    slug: "digital-packaging-print",
    name: "Digital Packaging Print",
    colour: "teal",
    what: "A single-pass CMYK digital print onto a range of packaging materials, producing full-colour, complex images with gradients.",
    bestFor: "Boxes, mailers, retail cartons and packaging needing photographic or gradient artwork",
    colourLimit: "Full CMYK digital print. Metallic, neon and closely matched PMS/RGB colours cannot be produced.",
    leadTime: "Dries instantly, so products can be shipped immediately",
    artwork: "Vector or bitmap at 300DPI at actual print size. Fonts should be converted to outlines/objects.",
    advantages: [
      "Ideal for producing full colour, complex images with gradients",
      "Variable data, including names, is available on select products",
      "Only one setup charge is required regardless of the number of print colours",
      "Dries instantly, so products can be shipped immediately",
      "Uses dye so there is no ink build-up",
    ],
    limitations: [
      "Some colours, including closely matched PMS, RGB, metallic and neon colours, cannot be produced",
      "Cannot print on dark coloured substrates as white ink cannot be printed underneath the artwork",
      "Edge-to-edge branding and large block colours cannot be achieved",
    ],
  },
  {
    slug: "digital-print",
    name: "Digital Print",
    colour: "cyan",
    what: "A CMYK digital print process for paper, vinyl and magnetic material used in the manufacture of labels, badges, fridge magnets and similar items.",
    bestFor: "Labels, badges, fridge magnets, stickers and promotional paper products",
    colourLimit: "Full CMYK digital print. Metallic and neon/fluorescent colours are not available.",
    leadTime: "Dries instantly, so products can be shipped immediately",
    artwork: "Vector or bitmap at 300DPI at actual print size. Add a 3mm bleed if artwork bleeds off the product. Fonts should be converted to outlines/objects.",
    advantages: [
      "Ideal for producing full colour, complex images with gradients",
      "Variable data including individual names is available on select products",
      "Only one set up charge is required regardless of the number of print colours",
      "Dries instantly so products can be shipped immediately",
      "Select products can be cut to custom shapes",
      "Edge-to-edge branding can be achieved on certain products",
    ],
    limitations: [
      "Metallic and neon/fluorescent colours are not available",
      "White print cannot be produced on kraft, clear, silver or gold stock",
      "Cannot print on dark coloured substrates as white ink cannot be printed underneath the artwork",
    ],
  },
  {
    slug: "direct-digital",
    name: "Direct Digital",
    colour: "green",
    what: "Direct digital printing involves the transfer of ink directly from the print heads of an inkjet machine to the product. It can be used to produce both full colour and closely matched spot colour branding on flat or slightly curved surfaces.",
    bestFor: "Coasters, glassware, flat panels, slightly curved products and items needing white underbase on dark surfaces",
    colourLimit: "Full colour plus white underbase. Metallic and neon/fluorescent colours cannot be reproduced.",
    leadTime: "Dried instantly, so products can be shipped immediately",
    artwork: "Vector or bitmap at 300DPI at actual print size. Add a 3mm bleed if artwork bleeds off the product.",
    advantages: [
      "Ideal for printing dark coloured products as a layer of white ink can be printed under the artwork",
      "Variable data including individual names is available on select products",
      "Dried instantly so products can be shipped immediately",
      "Offers larger print areas on many products and can print very close to the edge of flat products",
      "Only one set up charge is required regardless of the number of print colours",
    ],
    limitations: [
      "Some colours cannot be reproduced including metallic and neon/fluorescent colours",
      "The size of branding areas is limited on curved surfaces",
      "Larger print areas can be more expensive",
    ],
  },
  {
    slug: "faux-embroidery",
    name: "Faux Embroidery",
    colour: "orange",
    what: "A Colourflex® Transfer with the supplied artwork digitised to create a texture and depth that mimics traditional embroidery. Suitable for branding bags, apparel and other textile products with unlimited colours.",
    bestFor: "Caps, apparel, bags and textile products needing an embroidered look with unlimited colours",
    colourLimit: "Unlimited colours. Pantone matching is not available — artwork is matched to the closest thread colour with 3D shading that affects the final colour outcome. Metallic colours not available.",
    leadTime: "Can be shipped straight after being printed",
    artwork: "Vector and/or high-resolution JPEG. Bitmaps can be used, but insufficient resolution will affect output quality. Sans Serif fonts: min. height 4.5mm, 1.3mm thickness, 1mm letter spacing. Serif/Script fonts: min. height 5.5mm, 1.3mm thickness, 1mm letter spacing.",
    advantages: [
      "Durable, flexible branding for apparel that is machine washable with a soft-touch matte finish",
      "Eco-friendly water-based inks",
      "Efficient self-weeding technology",
      "Only one set up charge is required regardless of the number of print colours",
      "Can be shipped straight after being printed",
      "Can be applied to a larger range of products and positions",
      "Results on smaller sized prints is far better than can be achieved with conventional embroidery",
    ],
    limitations: [
      "Pantone colour matching is not available. Artwork will be matched to the closest available thread colour with a 3D shading that will affect the colour outcome",
      "Not suitable for fine details in the artwork – bold larger art is recommended to create the most realistic Faux Embroidery",
      "As the size of the design decreases, both stitch clarity and detail resolution be reduced",
      "Metallic colours not available",
    ],
  },
  {
    slug: "foil-printing",
    name: "Foil Printing",
    colour: "amber",
    what: "A printing method that applies a metallic foil onto a flat surface using heat and pressure. This method utilises modern digital foiling, which is more cost-effective and eliminates the need for plates or stamps, allowing for direct printing from a digital file to the product. The printing will inherit the texture of the substrate, and the available foil colour options include Gold, Silver and Copper.",
    bestFor: "Notebooks, diaries, journals and flat-surface products needing a premium metallic finish",
    colourLimit: "Gold, Silver and Copper foil options. Finish varies on soft-touch PU vs Standard PU and textured substrates.",
    leadTime: "Can be shipped as soon as printing is finished",
    artwork: "Vector artwork required. Fonts should be converted to outlines/objects. Minimum line thickness 0.4mm on smooth substrates and 1mm on textured substrates.",
    advantages: [
      "Higher perceived value than other forms of branding",
      "The product can be shipped as soon as printing is finished",
      "Offers variable data such as individual naming",
      "The foil is flexible which means it is suitable for softcover notebooks",
    ],
    limitations: [
      "Detailed artwork can get lost on textured substrates",
      "Min line thickness 0.4mm for smooth substrates",
      "Min line thickness 1mm for textured substrates",
    ],
  },
  {
    slug: "hot-stamping",
    name: "Hot Stamping",
    colour: "sand",
    what: "A printing method that creates an indented design on the product surface using a heated custom metal plate. This plate is pressed firmly onto the product surface, leaving a permanent impression of the artwork. It's often used on materials like wood.",
    bestFor: "Wooden products, natural materials, giftware and premium packaging",
    colourLimit: "Single tone — the natural impression of the heated plate on the substrate",
    leadTime: "Can be shipped as soon as heat pressing is finished",
    artwork: "Vector artwork required. Fonts should be converted to outlines/objects. Minimum line thickness 0.4mm.",
    advantages: [
      "Higher perceived value than other forms of branding",
      "The branding becomes part of the product and is permanent",
      "The product can be shipped as soon as heat pressing is finished",
      "Certain products can produce a two-tone, contrasting finish",
    ],
    limitations: [
      "Unable to print variable data such as individual naming",
      "Large block artwork can produce an inconsistent print result",
      "Minimum line thickness: 0.4mm",
    ],
  },
  {
    slug: "imitation-etch",
    name: "Imitation Etch",
    colour: "blue",
    what: "Imitation etch uses a special ink to produce an etch-like effect on glass products via pad or screen print.",
    bestFor: "Glassware, drinkware and curved or uneven glass products needing an etched look",
    colourLimit: "Single tone — frosted etch-like finish",
    leadTime: "Requires a curing period before the product can be shipped",
    artwork: "Vector editable artwork required. Fonts should be converted to outlines/objects.",
    advantages: [
      "Much more affordable than real etching",
      "Can brand curved or uneven products",
      "Produces a subtle finish with a higher perceived value that looks like etching",
    ],
    limitations: [
      "Halftones cannot be consistently reproduced",
      "The size of branding areas is limited on curved surfaces",
      "Requires a curing period before the product can be shipped",
      "Unable to print variable data",
    ],
  },
  {
    slug: "prism-digital-print",
    name: "Prism Digital Print",
    colour: "violet",
    what: "A UV-DTF (Direct to Film) process using CMYK + White + Varnish. UV inks print directly onto film, are cured by UV light, laminated and applied directly to the object like a sticker — eliminating the need for heat presses or powders. The result is a vibrant, durable and high-resolution logo with a gloss finish.",
    bestFor: "Hard surface products, personalisation, variable data including names and numbering",
    colourLimit: "Full colour with white underbase and gloss varnish",
    leadTime: "Can be shipped straight after printing",
    artwork: "Vector or bitmap artwork accepted. Supplied bitmaps must be higher than 300DPI at actual print size. Fonts should be converted to outlines/objects.",
    advantages: [
      "Produces vivid, full colour print with a gloss finish",
      "Long-lasting and resistant to scratching and fading",
      "Can be applied to most hard surfaces",
      "No need for heat presses or screens",
      "Ideal for personalisation and variable data, including names and numbering",
      "Efficient self-weeding technology",
      "Only one set up charge is required regardless of the number of print colours",
      "Can be shipped straight after printing",
    ],
    limitations: [
      "Not suitable for soft or flexible products",
      "Some colours cannot be reproduced including metallic and neon/fluorescent colours",
      "Minimum detail advised at 0.8mm",
      "Not suitable for designs with gradients that fade out to a transparency",
    ],
  },
  {
    slug: "puff-print",
    name: "Puff Print",
    colour: "orange",
    what: "A specialty Screen Print process used for branding apparel. Puff Print uses a special ink which expands during curing to create a raised, textured, three-dimensional finish.",
    bestFor: "Apparel, bold logos, large typography and simple graphic elements where a tactile look is desired",
    colourLimit: "One colour per artwork — exact colour matching cannot be guaranteed",
    leadTime: "Standard screen print lead time applies",
    artwork: "Vector artwork required. Supplied bitmaps must be higher than 300DPI at actual print size. Minimum line thickness 3mm. Minimum negative space/open gaps 4mm. Fonts should be converted to outlines/objects.",
    advantages: [
      "Adds a retail-style finish to garments",
      "Produces a highly tactile and eye-catching result",
      "Can be combined with one colour Screen Print to add dimension to your design",
      "Durable and long-lasting branding process",
    ],
    limitations: [
      "Not suitable for fine detail, thin lines, or gradients",
      "Small text and tight spacing may close during Puff Print expansion",
      "Exact colour matching cannot be guaranteed",
      "Puff Print expansion can vary slightly across different garment types",
      "Puff Print is available in one colour per artwork",
    ],
  },
  {
    slug: "resin-coated-finish",
    name: "Resin Coated Finish",
    colour: "cyan",
    what: "A CMYK branding process produced by printing artwork onto a vinyl material with strong adhesive on the reverse. The branded area is then coated with a crystal-clear resin. Once dry, the finished decal is applied to the product and the adhesive forms a permanent bond.",
    bestFor: "Keyrings, metal products and items needing a vivid full-colour image with a 3D domed effect",
    colourLimit: "Full colour CMYK — white, metallic gold, silver and neon colours cannot be printed",
    leadTime: "The resin needs to be cured for one day before shipping the product",
    artwork: "Vector or bitmap artwork accepted. Supplied bitmaps must be higher than 300DPI at actual print size. A 3mm bleed must be added if the artwork bleeds off the product.",
    advantages: [
      "Ideal for producing vivid full colour images as well as closely matched spot colour branding",
      "Produces a stunning 3D effect that elevates the perceived value of a product",
      "Variable data including individual names is available on select products",
      "Edge-to-edge branding can be achieved on the resin coated area",
      "Only one set up charge is required regardless of the number of print colours",
    ],
    limitations: [
      "Larger print areas can be more expensive",
      "White, metallic gold, silver and neon colours cannot be printed",
      "The resin needs to be cured for one day before shipping the product",
    ],
  },
  {
    slug: "rotary-digital-print",
    name: "Rotary Digital Print",
    colour: "teal",
    what: "Direct to product rotary digital printing involves the transfer of UV ink and a varnish coating from inkjet print heads. It is used to produce detailed gloss artwork using both closely matched spot colours and full colour branding.",
    bestFor: "Cylindrical products such as drinkware and bottles needing detailed full-colour gloss prints",
    colourLimit: "Full colour plus spot colour matching, with gloss varnish",
    leadTime: "Production speed is limited so lead times can be longer in some cases",
    artwork: "Vector or bitmap artwork accepted. Supplied bitmaps must be higher than 300DPI at actual print size. Fonts should be converted to outlines/objects.",
    advantages: [
      "Ideal for large or complex full colour gloss prints",
      "The print is dry and ready to ship as soon as the product is printed",
      "Only one setup charge is required regardless of the number of print colours",
      "No loss of print vibrancy, even on darker products",
    ],
    limitations: [
      "Production speed is limited so lead times can be longer in some cases",
      "Some colours cannot be reproduced including metallic and neon/fluorescent colours",
      "As the print does not wrap completely around the product, there is a small gap between the start and end of the print",
      "More expensive than other branding options",
    ],
  },
  {
    slug: "rotary-screen-print",
    name: "Rotary Screen Print",
    colour: "teal",
    what: "Screen Printing is achieved by forcing ink through a fine mesh screen with a squeegee onto the product. The rotary version is ideal for branding cylindrical objects with the same crisp, opaque finish as flat screen printing.",
    bestFor: "Cylindrical products such as drinkware, bottles and flat objects needing bold, opaque branding",
    colourLimit: "Up to 5 spot colours with tight multi-colour registration; fluorescent, metallic gold and silver inks available on select products",
    leadTime: "Most screen print inks dry quickly and can be shipped immediately after printing",
    artwork: "Editable vector artwork required. Fonts should be converted to outlines/objects.",
    advantages: [
      "Large print areas are possible on flat products",
      "Close PMS matches are possible on white or light-coloured products",
      "Most screen print inks dry quickly and can be shipped immediately after printing",
      "Fluorescent, metallic gold and silver inks are available on select textile products",
      "Many products can print with tight multi-colour registration, with some products able to be printed using up to five colours",
    ],
    limitations: [
      "Close PMS matches are more difficult on darker products and will only be approximate. In some instances, a white base will create a better print",
      "Unable to print variable data",
      "Each colour requires its own setup charge",
    ],
  },
  {
    slug: "silicone-digital-print",
    name: "Silicone Digital Print",
    colour: "cyan",
    what: "A CMYK+W digital branding process designed specifically for silicone surfaces. It produces crisp, clear, high-definition artwork with a matt finish that does not crack or fade with typical use.",
    bestFor: "Silicone products such as reusable cups, bands, sleeves and other flexible silicone items",
    colourLimit: "Full colour CMYK plus white underbase — metallic and neon/fluorescent colours cannot be reproduced",
    leadTime: "Standard digital print lead time applies",
    artwork: "Vector or bitmap artwork accepted. Supplied bitmaps must be higher than 300DPI at actual print size. Fonts should be converted to outlines/objects to avoid font conflicts.",
    advantages: [
      "Provides crisp, clear, high-definition artwork",
      "Durable, flexible branding that can be hand washed",
      "Perfect for printing dark coloured products as a layer of white ink can be printed under the artwork",
      "Ideal for producing full colour images as well as approximate spot colour branding",
      "Has a matt finish and does not crack or fade with typical use of product",
      "Only one set up charge is required regardless of the number of print colours",
    ],
    limitations: [
      "Some colours cannot be reproduced including metallic and neon/fluorescent colours",
      "Unable to print variable data",
      "Minimum detail is advised to be no finer than 0.7mm",
    ],
  },
];

export const artworkFaq = [
  {
    q: "What file format should I send?",
    a: "Vector artwork (AI, EPS or PDF) is ideal because it scales to any size without losing quality. If you only have a raster file, send the largest version you have at 300dpi — ideally a PNG with a transparent background.",
  },
  {
    q: "I only have a logo from our website. Is that enough?",
    a: "Often not. Web logos are usually 72dpi and too small to print cleanly. Send it through anyway — our studio will tell you honestly whether it will hold up, and can redraw it as vector for a one-off fee.",
  },
  {
    q: "How do you match our brand colours?",
    a: "Send your Pantone references and we match spot-colour methods to them exactly. Full-colour methods are converted to the closest CMYK build, and we can supply a pre-production sample if the colour is critical.",
  },
  {
    q: "Will I see a proof before production?",
    a: "Always. Every order gets a digital proof showing placement, size and colours, and nothing goes to production until you approve it in writing.",
  },
  {
    q: "Can you print onto dark products?",
    a: "Yes. Screen and digital methods can lay down a white underbase first so colours stay bright instead of sinking into the garment or bottle.",
  },
];
