/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as ColourGuideRouteImport } from './routes/colour-guide'
import { Route as DecorationRouteImport } from './routes/decoration'
import { Route as ImpactAwareRouteImport } from './routes/impact-aware'
import { Route as LookbookRouteImport } from './routes/lookbook'
import { Route as McpRouteImport } from './routes/mcp'
import { Route as QuoteRouteImport } from './routes/quote'
import { Route as Char91DotmcpChar93ListToolsRouteImport } from './routes/[.mcp]/list-tools'
import { Route as Char91DotwellKnownChar93OauthProtectedResourceRouteImport } from './routes/[.well-known]/oauth-protected-resource'
import { Route as AuthenticatedAdminRouteRouteImport } from './routes/_authenticated/admin/route'
import { Route as JobTokenRouteImport } from './routes/job.$token'
import { Route as PayTokenRouteImport } from './routes/pay.$token'
import { Route as ProductsIndexRouteImport } from './routes/products.index'
import { Route as ProductsCategoryRouteImport } from './routes/products.$category'
import { Route as ProofTokenRouteImport } from './routes/proof.$token'
import { Route as QTokenRouteImport } from './routes/q.$token'
import { Route as DotlovableOauthConsentRouteImport } from './routes/[.]lovable.oauth.consent'
import { Route as Char91DotmcpChar93InvokeToolToolRouteImport } from './routes/[.mcp]/invoke-tool/$tool'
import { Route as AuthenticatedAdminCatalogueRouteImport } from './routes/_authenticated/admin/catalogue'
import { Route as ApiPublicCatalogImageSplatRouteImport } from './routes/api/public/catalog-image.$'
import { Route as ApiPublicPaymentsWebhookRouteImport } from './routes/api/public/payments/webhook'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const ColourGuideRoute = ColourGuideRouteImport.update({
  id: '/colour-guide',
  path: '/colour-guide',
  getParentRoute: () => rootRouteImport,
} as any)
const DecorationRoute = DecorationRouteImport.update({
  id: '/decoration',
  path: '/decoration',
  getParentRoute: () => rootRouteImport,
} as any)
const ImpactAwareRoute = ImpactAwareRouteImport.update({
  id: '/impact-aware',
  path: '/impact-aware',
  getParentRoute: () => rootRouteImport,
} as any)
const LookbookRoute = LookbookRouteImport.update({
  id: '/lookbook',
  path: '/lookbook',
  getParentRoute: () => rootRouteImport,
} as any)
const McpRoute = McpRouteImport.update({
  id: '/mcp',
  path: '/mcp',
  getParentRoute: () => rootRouteImport,
} as any)
const QuoteRoute = QuoteRouteImport.update({
  id: '/quote',
  path: '/quote',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93ListToolsRoute =
  Char91DotmcpChar93ListToolsRouteImport.update({
    id: '/.mcp/list-tools',
    path: '/.mcp/list-tools',
    getParentRoute: () => rootRouteImport,
  } as any)
const Char91DotwellKnownChar93OauthProtectedResourceRoute =
  Char91DotwellKnownChar93OauthProtectedResourceRouteImport.update({
    id: '/.well-known/oauth-protected-resource',
    path: '/.well-known/oauth-protected-resource',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminRouteRoute = AuthenticatedAdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const JobTokenRoute = JobTokenRouteImport.update({
  id: '/job/$token',
  path: '/job/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const PayTokenRoute = PayTokenRouteImport.update({
  id: '/pay/$token',
  path: '/pay/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsIndexRoute = ProductsIndexRouteImport.update({
  id: '/products/',
  path: '/products/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProductsCategoryRoute = ProductsCategoryRouteImport.update({
  id: '/products/$category',
  path: '/products/$category',
  getParentRoute: () => rootRouteImport,
} as any)
const ProofTokenRoute = ProofTokenRouteImport.update({
  id: '/proof/$token',
  path: '/proof/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const QTokenRoute = QTokenRouteImport.update({
  id: '/q/$token',
  path: '/q/$token',
  getParentRoute: () => rootRouteImport,
} as any)
const DotlovableOauthConsentRoute = DotlovableOauthConsentRouteImport.update({
  id: '/.lovable/oauth/consent',
  path: '/.lovable/oauth/consent',
  getParentRoute: () => rootRouteImport,
} as any)
const Char91DotmcpChar93InvokeToolToolRoute =
  Char91DotmcpChar93InvokeToolToolRouteImport.update({
    id: '/.mcp/invoke-tool/$tool',
    path: '/.mcp/invoke-tool/$tool',
    getParentRoute: () => rootRouteImport,
  } as any)
const AuthenticatedAdminCatalogueRoute =
  AuthenticatedAdminCatalogueRouteImport.update({
    id: '/catalogue',
    path: '/catalogue',
    getParentRoute: () => AuthenticatedAdminRouteRoute,
  } as any)
const ApiPublicCatalogImageSplatRoute =
  ApiPublicCatalogImageSplatRouteImport.update({
    id: '/api/public/catalog-image/$',
    path: '/api/public/catalog-image/$',
    getParentRoute: () => rootRouteImport,
  } as any)
const ApiPublicPaymentsWebhookRoute =
  ApiPublicPaymentsWebhookRouteImport.update({
    id: '/api/public/payments/webhook',
    path: '/api/public/payments/webhook',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/colour-guide': typeof ColourGuideRoute
  '/decoration': typeof DecorationRoute
  '/impact-aware': typeof ImpactAwareRoute
  '/lookbook': typeof LookbookRoute
  '/mcp': typeof McpRoute
  '/quote': typeof QuoteRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/job/$token': typeof JobTokenRoute
  '/pay/$token': typeof PayTokenRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/proof/$token': typeof ProofTokenRoute
  '/q/$token': typeof QTokenRoute
  '/products/': typeof ProductsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/catalogue': typeof AuthenticatedAdminCatalogueRoute
  '/api/public/catalog-image/$': typeof ApiPublicCatalogImageSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/colour-guide': typeof ColourGuideRoute
  '/decoration': typeof DecorationRoute
  '/impact-aware': typeof ImpactAwareRoute
  '/lookbook': typeof LookbookRoute
  '/mcp': typeof McpRoute
  '/quote': typeof QuoteRoute
  '/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/job/$token': typeof JobTokenRoute
  '/pay/$token': typeof PayTokenRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/proof/$token': typeof ProofTokenRoute
  '/q/$token': typeof QTokenRoute
  '/products': typeof ProductsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/admin/catalogue': typeof AuthenticatedAdminCatalogueRoute
  '/api/public/catalog-image/$': typeof ApiPublicCatalogImageSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/colour-guide': typeof ColourGuideRoute
  '/decoration': typeof DecorationRoute
  '/impact-aware': typeof ImpactAwareRoute
  '/lookbook': typeof LookbookRoute
  '/mcp': typeof McpRoute
  '/quote': typeof QuoteRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteRouteWithChildren
  '/.mcp/list-tools': typeof Char91DotmcpChar93ListToolsRoute
  '/.well-known/oauth-protected-resource': typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  '/job/$token': typeof JobTokenRoute
  '/pay/$token': typeof PayTokenRoute
  '/products/$category': typeof ProductsCategoryRoute
  '/proof/$token': typeof ProofTokenRoute
  '/q/$token': typeof QTokenRoute
  '/products/': typeof ProductsIndexRoute
  '/.lovable/oauth/consent': typeof DotlovableOauthConsentRoute
  '/.mcp/invoke-tool/$tool': typeof Char91DotmcpChar93InvokeToolToolRoute
  '/_authenticated/admin/catalogue': typeof AuthenticatedAdminCatalogueRoute
  '/api/public/catalog-image/$': typeof ApiPublicCatalogImageSplatRoute
  '/api/public/payments/webhook': typeof ApiPublicPaymentsWebhookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/colour-guide'
    | '/decoration'
    | '/impact-aware'
    | '/lookbook'
    | '/mcp'
    | '/quote'
    | '/admin'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/job/$token'
    | '/pay/$token'
    | '/products/$category'
    | '/proof/$token'
    | '/q/$token'
    | '/products/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/catalogue'
    | '/api/public/catalog-image/$'
    | '/api/public/payments/webhook'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/colour-guide'
    | '/decoration'
    | '/impact-aware'
    | '/lookbook'
    | '/mcp'
    | '/quote'
    | '/admin'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/job/$token'
    | '/pay/$token'
    | '/products/$category'
    | '/proof/$token'
    | '/q/$token'
    | '/products'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/admin/catalogue'
    | '/api/public/catalog-image/$'
    | '/api/public/payments/webhook'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/colour-guide'
    | '/decoration'
    | '/impact-aware'
    | '/lookbook'
    | '/mcp'
    | '/quote'
    | '/_authenticated/admin'
    | '/.mcp/list-tools'
    | '/.well-known/oauth-protected-resource'
    | '/job/$token'
    | '/pay/$token'
    | '/products/$category'
    | '/proof/$token'
    | '/q/$token'
    | '/products/'
    | '/.lovable/oauth/consent'
    | '/.mcp/invoke-tool/$tool'
    | '/_authenticated/admin/catalogue'
    | '/api/public/catalog-image/$'
    | '/api/public/payments/webhook'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  ColourGuideRoute: typeof ColourGuideRoute
  DecorationRoute: typeof DecorationRoute
  ImpactAwareRoute: typeof ImpactAwareRoute
  LookbookRoute: typeof LookbookRoute
  McpRoute: typeof McpRoute
  QuoteRoute: typeof QuoteRoute
  Char91DotmcpChar93ListToolsRoute: typeof Char91DotmcpChar93ListToolsRoute
  Char91DotwellKnownChar93OauthProtectedResourceRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRoute
  JobTokenRoute: typeof JobTokenRoute
  PayTokenRoute: typeof PayTokenRoute
  ProductsCategoryRoute: typeof ProductsCategoryRoute
  ProofTokenRoute: typeof ProofTokenRoute
  QTokenRoute: typeof QTokenRoute
  ProductsIndexRoute: typeof ProductsIndexRoute
  DotlovableOauthConsentRoute: typeof DotlovableOauthConsentRoute
  Char91DotmcpChar93InvokeToolToolRoute: typeof Char91DotmcpChar93InvokeToolToolRoute
  ApiPublicCatalogImageSplatRoute: typeof ApiPublicCatalogImageSplatRoute
  ApiPublicPaymentsWebhookRoute: typeof ApiPublicPaymentsWebhookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/colour-guide': {
      id: '/colour-guide'
      path: '/colour-guide'
      fullPath: '/colour-guide'
      preLoaderRoute: typeof ColourGuideRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/decoration': {
      id: '/decoration'
      path: '/decoration'
      fullPath: '/decoration'
      preLoaderRoute: typeof DecorationRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/impact-aware': {
      id: '/impact-aware'
      path: '/impact-aware'
      fullPath: '/impact-aware'
      preLoaderRoute: typeof ImpactAwareRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/lookbook': {
      id: '/lookbook'
      path: '/lookbook'
      fullPath: '/lookbook'
      preLoaderRoute: typeof LookbookRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mcp': {
      id: '/mcp'
      path: '/mcp'
      fullPath: '/mcp'
      preLoaderRoute: typeof McpRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/quote': {
      id: '/quote'
      path: '/quote'
      fullPath: '/quote'
      preLoaderRoute: typeof QuoteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/list-tools': {
      id: '/.mcp/list-tools'
      path: '/.mcp/list-tools'
      fullPath: '/.mcp/list-tools'
      preLoaderRoute: typeof Char91DotmcpChar93ListToolsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.well-known/oauth-protected-resource': {
      id: '/.well-known/oauth-protected-resource'
      path: '/.well-known/oauth-protected-resource'
      fullPath: '/.well-known/oauth-protected-resource'
      preLoaderRoute: typeof Char91DotwellKnownChar93OauthProtectedResourceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/job/$token': {
      id: '/job/$token'
      path: '/job/$token'
      fullPath: '/job/$token'
      preLoaderRoute: typeof JobTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pay/$token': {
      id: '/pay/$token'
      path: '/pay/$token'
      fullPath: '/pay/$token'
      preLoaderRoute: typeof PayTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/': {
      id: '/products/'
      path: '/products'
      fullPath: '/products/'
      preLoaderRoute: typeof ProductsIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/products/$category': {
      id: '/products/$category'
      path: '/products/$category'
      fullPath: '/products/$category'
      preLoaderRoute: typeof ProductsCategoryRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/proof/$token': {
      id: '/proof/$token'
      path: '/proof/$token'
      fullPath: '/proof/$token'
      preLoaderRoute: typeof ProofTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/q/$token': {
      id: '/q/$token'
      path: '/q/$token'
      fullPath: '/q/$token'
      preLoaderRoute: typeof QTokenRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.lovable/oauth/consent': {
      id: '/.lovable/oauth/consent'
      path: '/.lovable/oauth/consent'
      fullPath: '/.lovable/oauth/consent'
      preLoaderRoute: typeof DotlovableOauthConsentRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/.mcp/invoke-tool/$tool': {
      id: '/.mcp/invoke-tool/$tool'
      path: '/.mcp/invoke-tool/$tool'
      fullPath: '/.mcp/invoke-tool/$tool'
      preLoaderRoute: typeof Char91DotmcpChar93InvokeToolToolRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/admin/catalogue': {
      id: '/_authenticated/admin/catalogue'
      path: '/catalogue'
      fullPath: '/admin/catalogue'
      preLoaderRoute: typeof AuthenticatedAdminCatalogueRouteImport
      parentRoute: typeof AuthenticatedAdminRouteRoute
    }
    '/api/public/catalog-image/$': {
      id: '/api/public/catalog-image/$'
      path: '/api/public/catalog-image/$'
      fullPath: '/api/public/catalog-image/$'
      preLoaderRoute: typeof ApiPublicCatalogImageSplatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/payments/webhook': {
      id: '/api/public/payments/webhook'
      path: '/api/public/payments/webhook'
      fullPath: '/api/public/payments/webhook'
      preLoaderRoute: typeof ApiPublicPaymentsWebhookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface AuthenticatedAdminRouteRouteChildren {
  AuthenticatedAdminCatalogueRoute: typeof AuthenticatedAdminCatalogueRoute
}

const AuthenticatedAdminRouteRouteChildren: AuthenticatedAdminRouteRouteChildren =
  {
    AuthenticatedAdminCatalogueRoute: AuthenticatedAdminCatalogueRoute,
  }

const AuthenticatedAdminRouteRouteWithChildren =
  AuthenticatedAdminRouteRoute._addFileChildren(
    AuthenticatedAdminRouteRouteChildren,
  )

interface AuthenticatedRouteRouteChildren {
  AuthenticatedAdminRouteRoute: typeof AuthenticatedAdminRouteRouteWithChildren
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedAdminRouteRoute: AuthenticatedAdminRouteRouteWithChildren,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  ColourGuideRoute: ColourGuideRoute,
  DecorationRoute: DecorationRoute,
  ImpactAwareRoute: ImpactAwareRoute,
  LookbookRoute: LookbookRoute,
  McpRoute: McpRoute,
  QuoteRoute: QuoteRoute,
  Char91DotmcpChar93ListToolsRoute: Char91DotmcpChar93ListToolsRoute,
  Char91DotwellKnownChar93OauthProtectedResourceRoute:
    Char91DotwellKnownChar93OauthProtectedResourceRoute,
  JobTokenRoute: JobTokenRoute,
  PayTokenRoute: PayTokenRoute,
  ProductsCategoryRoute: ProductsCategoryRoute,
  ProofTokenRoute: ProofTokenRoute,
  QTokenRoute: QTokenRoute,
  ProductsIndexRoute: ProductsIndexRoute,
  DotlovableOauthConsentRoute: DotlovableOauthConsentRoute,
  Char91DotmcpChar93InvokeToolToolRoute: Char91DotmcpChar93InvokeToolToolRoute,
  ApiPublicCatalogImageSplatRoute: ApiPublicCatalogImageSplatRoute,
  ApiPublicPaymentsWebhookRoute: ApiPublicPaymentsWebhookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
